select * from HEALTHCAREDATA
 where CITY_CODE_HOSPITAL=2;
 select *from HEALTHCAREDATA
 where AVAILABLE_EXTRA_ROOMS_IN_HOSPITAL>3;
 INSERT into HEALTHCAREDATA(CITY_CODE_PATIENT,CASE_ID,HOSPITAL_CODE,CITY_CODE_HOSPITAL,AVAILABLE_EXTRA_ROOMS_IN_HOSPITAL)
 values(8.0,513886,23,1,5);